version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: effective
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/pgdata
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg: